### PR TITLE
11-21-19 map-data update

### PR DESCRIPTION
**Pull request by rpitingolo**
@ddorio Hi Dave, can you please use this data to populate the development site for us to review? Thanks!

### CODE REVIEW

**Comment by ddorio** [comment]
@rpitingolo 

I have this in the queue.  Is it OK if it happens after Thanksgiving?

**Comment by rpitingolo** [comment]
@ddorio if possible we'd really like to review it next week since there will surely be bugs that I'll have to work through.

**Comment by ddorio** [comment]
@rpitingolo OK. Let me re-arrange a few things.

**Comment by rpitingolo** [comment]
@ddorio thanks, Dave.

**Comment by rpitingolo** [comment]
@ddorio hi Dave. Can you let me know when the dev site will be ready?

**Comment by ddorio** [comment]
@rpitingolo 

How can I check that the data are updated? Are there new years at specific levels or for specific indicators?

**Comment by rpitingolo** [comment]
@ddorio yeah, there are some new years of crime data and hmda data, and some new indicators in the "connection" category for broadband internet access.

**Pull request merged**
